### ISSUE TITLE
Acrescentar Lista para apuração

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/teletrabalho-atividades#1]
@fjuniorr, podemos acrescentar uma lista para padronizar o campo "Apuração" e inclui-lo no arquivo [google sheet](https://docs.google.com/spreadsheets/d/19HVY7H0Qlhh78zSVB8tsPBHvfs-Dyz18B40lOTEOGCQ/edit#gid=999714186), ou podemos já pensar na migração deste processo para o github project?

**Comment by fjuniorr** [comment]
Eu ainda não cheguei a preencher um relatório de atividades de encerramento do mês do ponto digital, mas eu entendo o campo `Apuração` como sendo um número, igual a `Quantidade`.

Nesse caso não precisa de padronização.

**Comment by gabrielbdornas** [comment]
@fjuniorr, perfeito!
